### ISSUE TITLE
Suggestion: If you replace the Packager model can you share it with Aquila?

### ISSUE THREAD

**Issue by catreplicators** [Jarno458/UsefulLiquidBiofuelMod#1]
The Small Refinery mod by Aquila is missing a good model, and a Mixer model would probably also be good for the Small Refinery.

**Comment by Jarno458** [comment]
Them mixer will indeed be a small building with 1 fluid and 1 solid in, and 1 fluid out
if that would be good for Aquila than i think i dont think ill mind sharing it
But i think the small refinery also needs a solid output, i dont plan on having that on my mixer
